# Generated by Django 6.0.7 on 2026-08-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
        ('plants', '0002_plant_care_notes_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growing_trials', to='containers.container')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growing_trials', to='plants.plant')),
            ],
        ),
    ]
